### ISSUE TITLE
Globalisation issue in pull_config.py

### ISSUE THREAD

**Issue by pwalker99** [ktanushree/prismasdwan_policy_config#1]
When running the following script I got the corresponding error:
```
$ python3 pull_policy.py -PT path --output production_path_policy.yml
INFO: Building translation dicts
Traceback (most recent call last):
  File "/home/ec2-user/prismasdwan_policy_config/pull_policy.py", line 2207, in <module>
    go()
  File "/home/ec2-user/prismasdwan_policy_config/pull_policy.py", line 2163, in go
    pull_policy_path(cgx_session=cgx_session, config_file=filename, reset_config=False)
  File "/home/ec2-user/prismasdwan_policy_config/pull_policy.py", line 1863, in pull_policy_path
    CONFIG[NETWORK_POLICY_STACKS] = [{stackname: stack_name_config[stackname]} for stackname in
UnboundLocalError: local variable 'CONFIG' referenced before assignment
```
I was able to fix this in my local repo by adding "global CONFIG" so that the pull_policy_path function is able to write to the CONFIG variable. The same issue can be observed in the other functions **(pull_policy_qos, pull_policy_security, pull_policy_nat)** because global isn't declared before trying to write to CONFIG which is declared outside the scope of the function.

**Comment by ktanushree** [comment]
Hi @pwalker99 This is fixed in 1.0.0b3. Thank you!
