### ISSUE TITLE
Running ./pull_policy.py for any such (path, Qos, security) getting error

### ISSUE THREAD

**Issue by Hemant40** [ktanushree/prismasdwan_policy_config#3]
Running ./pull_policy.py for any such (path, qos, nat security) getting error

(prismasdwan_policy_config) root@ubuntuserver:/home/ubuntu/Hemant/katanushree_policysdwan/orangeshop_sdwan/prismasdwan_policy_config# ./pull_policy.py -PT all --output allpolicyconfig.yml
INFO: Building translation dicts
Traceback (most recent call last):
  File "./pull_policy.py", line 2209, in <module>
    go()
  File "./pull_policy.py", line 2186, in go
    pull_policy_path(cgx_session=cgx_session, config_file=filename, reset_config=False)
  File "./pull_policy.py", line 1862, in pull_policy_path
    CONFIG[NETWORK_POLICY_STACKS] = [{stackname: stack_name_config[stackname]} for stackname in
UnboundLocalError: local variable 'CONFIG' referenced before assignment

(prismasdwan_policy_config) root@ubuntuserver:/home/ubuntu/Hemant/katanushree_policysdwan/orangeshop_sdwan/prismasdwan_policy_config# ./pull_policy.py -PT qos
INFO: Building translation dicts
Traceback (most recent call last):
  File "./pull_policy.py", line 2209, in <module>
    go()
  File "./pull_policy.py", line 2170, in go
    pull_policy_qos(cgx_session=cgx_session, config_file=filename, reset_config=False)
  File "./pull_policy.py", line 1920, in pull_policy_qos
    CONFIG[PRIORITY_POLICY_STACKS] = [{stackname: stack_name_config[stackname]} for stackname in
UnboundLocalError: local variable 'CONFIG' referenced before assignment

(prismasdwan_policy_config) root@ubuntuserver:/home/ubuntu/Hemant/katanushree_policysdwan/orangeshop_sdwan/prismasdwan_policy_config# ./pull_policy.py -PT security
INFO: Building translation dicts
Traceback (most recent call last):
  File "./pull_policy.py", line 2209, in <module>
    go()
  File "./pull_policy.py", line 2180, in go
    pull_policy_security(cgx_session=cgx_session, config_file=filename, reset_config=False)
  File "./pull_policy.py", line 2039, in pull_policy_security
    CONFIG[SECURITY_POLICY_STACKS] = [{stackname: stack_name_config[stackname]} for stackname in
UnboundLocalError: local variable 'CONFIG' referenced before assignment

(prismasdwan_policy_config) root@ubuntuserver:/home/ubuntu/Hemant/katanushree_policysdwan/orangeshop_sdwan/prismasdwan_policy_config# ./pull_policy.py -PT nat 
INFO: Building translation dicts
Traceback (most recent call last):
  File "./pull_policy.py", line 2209, in <module>
    go()
  File "./pull_policy.py", line 2175, in go
    pull_policy_nat(cgx_session=cgx_session, config_file=filename, reset_config=False)
  File "./pull_policy.py", line 1979, in pull_policy_nat
    CONFIG[NAT_POLICY_STACKS] = [{stackname: stack_name_config[stackname]} for stackname in stack_name_config.keys()]
UnboundLocalError: local variable 'CONFIG' referenced before assignment

**Comment by ktanushree** [comment]
Version 1.0.0 b4 has the fix for this issue.
